version: '3.8'

services:
  customer_service:
    build: ./customerService
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017/

  order_service:
    build: ./orderService
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://mongo:27017/

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"