name: Create and publish Order Service

on:
  workflow_run:
    workflows: ["Run Unit Tests on Order Service"]
    types:
      - completed

env:
  REPOSITORY: order-service
  RPATH: order_service
  
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-and-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ env.REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image for ${{ env.REPOSITORY }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.RPATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            conn_str=${{ secrets.CONN_STR }}
            rabbit_username=${{ secrets.RABBIT_USERNAME }}
            rabbit_password=${{ secrets.RABBIT_PASSWORD }}
            ip=${{ secrets.IP }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send payload
        run: |
          JSON_DATA='{"repository": "${{ env.REPOSITORY }}"}'
          ENDPOINT_URL="${{ secrets.WEBHOOK_URL }}"
          curl -X POST -H "Content-Type: application/json" -d "$JSON_DATA" "$ENDPOINT_URL"