name: Create and publish package

on:
  push:
    branches:
      - main
    paths:
      - 'order_service/**'

env:
  REPOSITORY: order-service
  RPATH: order_service
  
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  WEBHOOK_URL: http:/193.164.4.17:5000/webhook
  
  conn_str: "mongodb://MainAdmin:X6CN74SjdffTz9Pz@193.164.4.17:27017/"
  rabbit_username: "guest"
  rabbit_password: "Xdm@LtkdEoa5FHkM"
  ip: "193.164.4.17" 


jobs:
  build-and-push-image:
    if: ${{ contains(github.event.head_commit.message, '${{ env.RPATH }}') || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ env.REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image for ${{ env.REPOSITORY }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.RPATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            conn_str=${{ env.conn_str }}
            rabbit_username=${{ env.rabbit_username }}
            rabbit_password=${{ env.rabbit_password }}
            ip=${{ env.ip }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send payload
        run: |
          JSON_DATA='{"repository": "${{ env.REPOSITORY }}"}'
          ENDPOINT_URL="${{ env.WEBHOOK_URL }}"
          curl -X POST -H "Content-Type: application/json" -d "$JSON_DATA" "$ENDPOINT_URL"