name: Run Unit Tests on Customer Service

on:
  push:
    branches:
      - main
    paths:
      - 'customer_service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      conn_str: ${{ secrets.CONN_STR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd customer_service
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd customer_service
        pytest app/test_main.py -s  --disable-warnings